# Generated by Django 3.1.2 on 2021-03-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_todo1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TODO1',
        ),
    ]
