# Generated by Django 3.1.2 on 2021-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_delete_todo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', '1️⃣'), ('2', '2'), ('3', '3️⃣'), ('4', '4️⃣'), ('5', '5️⃣')], max_length=2),
        ),
    ]
